<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright 2013-2025 chronicle.software; SPDX-License-Identifier: Apache-2.0

-->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.openhft</groupId>
        <artifactId>java-parent-pom</artifactId>
        <version>1.27ea2-SNAPSHOT</version>
        <relativePath />
    </parent>

    <artifactId>chronicle-test-framework-parent</artifactId>
    <version>2.27ea3-SNAPSHOT</version>
    <name>OpenHFT/Chronicle-Test-Framework (Parent)</name>
    <description>Build parent for Chronicle Test Framework and JUnit adapters</description>
    <packaging>pom</packaging>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>net.openhft</groupId>
                <artifactId>third-party-bom</artifactId>
                <version>3.27ea7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <modules>
        <module>core</module>
        <module>junit4</module>
        <module>junit5</module>
        <module>consumer-simulations/junit4-consumer</module>
        <module>consumer-simulations/junit5-consumer</module>
    </modules>

    <repositories>
        <repository>
            <id>chronicle-enterprise-snapshots</id>
            <name>Snapshot Repository</name>
            <url>
                https://nexus.chronicle.software/content/repositories/snapshots
            </url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>chronicle-enterprise-release</id>
            <url>
                https://nexus.chronicle.software/content/repositories/releases
            </url>
            <releases>
                <enabled>true</enabled>
            </releases>
        </repository>
    </repositories>

    <scm>
        <url>scm:git:git@github.com:OpenHFT/Chronicle-Test-Framework.git</url>
        <connection>scm:git:git@github.com:OpenHFT/Chronicle-Test-Framework.git</connection>
        <developerConnection>scm:git:git@github.com:OpenHFT/Chronicle-Test-Framework.git
        </developerConnection>
        <tag>master</tag>
    </scm>

</project>

